import { Recipe } from "../api/RecipeApiType"

const dummyRecipes: Recipe[] = [
  {
    userId: 1,
    id: 1,
    name: "Spaghetti Bolognese",
    totalTime: "45 minutes",
    difficulty: "Medium",
    difficultyScore: 3,
    ingredients: [
      { ingredient: "Spaghetti", quantity: "200g" },
      { ingredient: "Ground beef", quantity: "300g" },
      { ingredient: "Tomato sauce", quantity: "400ml" },
      { ingredient: "Garlic", quantity: "2 cloves" },
      { ingredient: "Onion", quantity: "1" },
    ],
    steps: [
      { id: 1, step: "Boil spaghetti according to package instructions." },
      { id: 2, step: "Sauté onion and garlic in a pan." },
      { id: 3, step: "Add ground beef and cook until browned." },
      { id: 4, step: "Stir in tomato sauce and simmer for 20 minutes." },
      { id: 5, step: "Serve sauce over spaghetti." },
    ],
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    savedAt: "2024-12-01T12:30:00Z",
  },
  {
    userId: 2,
    id: 2,
    name: "Chicken Curry",
    totalTime: "50 minutes",
    difficulty: "Hard",
    difficultyScore: 4,
    ingredients: [
      { ingredient: "Chicken breast", quantity: "500g" },
      { ingredient: "Curry paste", quantity: "2 tbsp" },
      { ingredient: "Coconut milk", quantity: "400ml" },
      { ingredient: "Onion", quantity: "1" },
      { ingredient: "Garlic", quantity: "3 cloves" },
    ],
    steps: [
      { id: 1, step: "Cut chicken into bite-sized pieces." },
      { id: 2, step: "Sauté onion and garlic in a pot." },
      { id: 3, step: "Add curry paste and cook for 2 minutes." },
      { id: 4, step: "Add chicken and cook until browned." },
      { id: 5, step: "Pour in coconut milk and simmer for 30 minutes." },
    ],
    createdAt: "2024-12-02T14:00:00Z",
    updatedAt: "2024-12-02T14:00:00Z",
    savedAt: "2024-12-02T14:40:00Z",
  },
  {
    userId: 3,
    id: 3,
    name: "Caesar Salad",
    totalTime: "15 minutes",
    difficulty: "Easy",
    difficultyScore: 1,
    ingredients: [
      { ingredient: "Lettuce", quantity: "1 head" },
      { ingredient: "Caesar dressing", quantity: "4 tbsp" },
      { ingredient: "Parmesan cheese", quantity: "50g" },
      { ingredient: "Croutons", quantity: "1 cup" },
    ],
    steps: [
      { id: 1, step: "Wash and chop the lettuce." },
      { id: 2, step: "Toss lettuce with Caesar dressing." },
      { id: 3, step: "Sprinkle with parmesan cheese and croutons." },
      { id: 4, step: "Serve immediately." },
    ],
    createdAt: "2024-12-03T16:00:00Z",
    updatedAt: "2024-12-03T16:00:00Z",
    savedAt: "2024-12-03T16:05:00Z",
  },
  {
    userId: 4,
    id: 4,
    name: "Pancakes",
    totalTime: "20 minutes",
    difficulty: "Easy",
    difficultyScore: 1,
    ingredients: [
      { ingredient: "Flour", quantity: "200g" },
      { ingredient: "Milk", quantity: "300ml" },
      { ingredient: "Egg", quantity: "1" },
      { ingredient: "Baking powder", quantity: "1 tsp" },
      { ingredient: "Sugar", quantity: "2 tbsp" },
    ],
    steps: [
      { id: 1, step: "Mix flour, milk, egg, baking powder, and sugar in a bowl." },
      { id: 2, step: "Heat a pan and pour in batter." },
      { id: 3, step: "Cook until bubbles form, then flip and cook until golden." },
      { id: 4, step: "Serve with syrup or toppings." },
    ],
    createdAt: "2024-12-04T09:00:00Z",
    updatedAt: "2024-12-04T09:00:00Z",
    savedAt: "2024-12-04T09:10:00Z",
  },
  {
    userId: 5,
    id: 5,
    name: "Beef Tacos",
    totalTime: "30 minutes",
    difficulty: "Medium",
    difficultyScore: 3,
    ingredients: [
      { ingredient: "Ground beef", quantity: "400g" },
      { ingredient: "Taco shells", quantity: "8" },
      { ingredient: "Lettuce", quantity: "1 head" },
      { ingredient: "Cheddar cheese", quantity: "100g" },
      { ingredient: "Sour cream", quantity: "4 tbsp" },
    ],
    steps: [
      { id: 1, step: "Cook ground beef in a pan until browned." },
      { id: 2, step: "Warm taco shells in the oven." },
      { id: 3, step: "Fill taco shells with beef, lettuce, cheese, and sour cream." },
      { id: 4, step: "Serve with salsa and enjoy." },
    ],
    createdAt: "2024-12-05T11:00:00Z",
    updatedAt: "2024-12-05T11:00:00Z",
    savedAt: "2024-12-05T11:20:00Z",
  },
  {
    userId: 6,
    id: 6,
    name: "Vegetable Stir-fry",
    totalTime: "25 minutes",
    difficulty: "Easy",
    difficultyScore: 2,
    ingredients: [
      { ingredient: "Broccoli", quantity: "1 head" },
      { ingredient: "Carrot", quantity: "2" },
      { ingredient: "Bell pepper", quantity: "1" },
      { ingredient: "Soy sauce", quantity: "3 tbsp" },
    ],
    steps: [
      { id: 1, step: "Chop vegetables into bite-sized pieces." },
      { id: 2, step: "Heat oil in a wok and stir-fry vegetables." },
      { id: 3, step: "Add soy sauce and cook for another 5 minutes." },
      { id: 4, step: "Serve hot." },
    ],
    createdAt: "2024-12-06T13:00:00Z",
    updatedAt: "2024-12-06T13:00:00Z",
    savedAt: "2024-12-06T13:15:00Z",
  },
  {
    userId: 7,
    id: 7,
    name: "Fish Tacos",
    totalTime: "40 minutes",
    difficulty: "Medium",
    difficultyScore: 3,
    ingredients: [
      { ingredient: "White fish fillets", quantity: "400g" },
      { ingredient: "Taco shells", quantity: "8" },
      { ingredient: "Cabbage", quantity: "1/2 head" },
      { ingredient: "Lime", quantity: "1" },
      { ingredient: "Cilantro", quantity: "2 tbsp" },
    ],
    steps: [
      { id: 1, step: "Cook fish fillets in a pan." },
      { id: 2, step: "Warm taco shells in the oven." },
      { id: 3, step: "Shred cabbage and prepare toppings." },
      { id: 4, step: "Fill taco shells with fish, cabbage, lime, and cilantro." },
      { id: 5, step: "Serve with hot sauce." },
    ],
    createdAt: "2024-12-07T17:00:00Z",
    updatedAt: "2024-12-07T17:00:00Z",
    savedAt: "2024-12-07T17:20:00Z",
  },
  {
    userId: 8,
    id: 8,
    name: "Apple Pie",
    totalTime: "60 minutes",
    difficulty: "Hard",
    difficultyScore: 4,
    ingredients: [
      { ingredient: "Apple", quantity: "4" },
      { ingredient: "Sugar", quantity: "100g" },
      { ingredient: "Flour", quantity: "200g" },
      { ingredient: "Butter", quantity: "100g" },
      { ingredient: "Cinnamon", quantity: "1 tsp" },
    ],
    steps: [
      { id: 1, step: "Preheat the oven to 180°C." },
      { id: 2, step: "Peel and slice the apples." },
      { id: 3, step: "Mix apples with sugar and cinnamon." },
      { id: 4, step: "Roll out pie crust and fill with apple mixture." },
      { id: 5, step: "Bake for 45 minutes or until golden." },
    ],
    createdAt: "2024-12-08T18:00:00Z",
    updatedAt: "2024-12-08T18:00:00Z",
    savedAt: "2024-12-08T18:30:00Z",
  },
  {
    userId: 9,
    id: 9,
    name: "Chocolate Cake",
    totalTime: "90 minutes",
    difficulty: "Hard",
    difficultyScore: 5,
    ingredients: [
      { ingredient: "Flour", quantity: "200g" },
      { ingredient: "Sugar", quantity: "150g" },
      { ingredient: "Cocoa powder", quantity: "50g" },
      { ingredient: "Eggs", quantity: "2" },
      { ingredient: "Butter", quantity: "100g" },
    ],
    steps: [
      { id: 1, step: "Preheat the oven to 180°C." },
      { id: 2, step: "Mix dry ingredients together." },
      { id: 3, step: "Add wet ingredients and mix until smooth." },
      { id: 4, step: "Pour into a cake tin and bake for 45 minutes." },
      { id: 5, step: "Cool and frost with chocolate icing." },
    ],
    createdAt: "2024-12-09T20:00:00Z",
    updatedAt: "2024-12-09T20:00:00Z",
    savedAt: "2024-12-09T20:40:00Z",
  },
];

export default dummyRecipes;